export enum MixingResult {
  VALID = 'VALID',

  MASTER_BATCH_NOT_FOUND = 'MASTER_BATCH_NOT_FOUND',
  MASTER_BATCH_ALREADY_USED = 'MASTER_BATCH_ALREADY_USED',

  WRONG_QR = 'WRONG_QR',
  WRONG_RECIPE = 'WRONG_RECIPE',
  WRONG_BATCH = 'WRONG_BATCH',
  WRONG_STAGE = 'WRONG_STAGE',

  PROCESS_ALREADY_DONE = 'PROCESS_ALREADY_DONE',

  DUPLICATE_SCAN = 'DUPLICATE_SCAN',

  WEIGH_NOT_DONE = 'WEIGH_NOT_DONE',
}
